export interface Hotzone {
  id: string;
  name: string;
  station: string;
  line: string;
  lat: number;
  lng: number;
  taxiScore: number; // 1-5, 심야 택시 가용성
  description: string;
}

export const HOTZONES: Hotzone[] = [
  {
    id: "gangnam",
    name: "강남",
    station: "강남역",
    line: "2호선",
    lat: 37.4979,
    lng: 127.0276,
    taxiScore: 5,
    description: "최대 상권, 심야 택시 최강",
  },
  {
    id: "yeoksam",
    name: "역삼/선릉",
    station: "역삼역",
    line: "2호선",
    lat: 37.5008,
    lng: 127.0364,
    taxiScore: 4,
    description: "직장인 회식 메카",
  },
  {
    id: "sinsa",
    name: "압구정/신사",
    station: "신사역",
    line: "3호선",
    lat: 37.5172,
    lng: 127.0200,
    taxiScore: 4,
    description: "고급 다이닝, 분위기 좋은 바",
  },
  {
    id: "hongdae",
    name: "홍대",
    station: "홍대입구역",
    line: "2호선",
    lat: 37.5572,
    lng: 126.9237,
    taxiScore: 4,
    description: "젊고 다양한 선택지, 가성비",
  },
  {
    id: "yeonnam",
    name: "연남/연희",
    station: "홍대입구역",
    line: "2호선",
    lat: 37.5645,
    lng: 126.9259,
    taxiScore: 3,
    description: "감성 식당, 조용한 분위기",
  },
  {
    id: "seongsu",
    name: "성수",
    station: "성수역",
    line: "2호선",
    lat: 37.5445,
    lng: 127.0564,
    taxiScore: 3,
    description: "요즘 가장 핫한 지역, 감성 레스토랑",
  },
  {
    id: "itaewon",
    name: "이태원/한남",
    station: "이태원역",
    line: "6호선",
    lat: 37.5340,
    lng: 126.9944,
    taxiScore: 4,
    description: "다국적 다이닝, 프리미엄 바",
  },
  {
    id: "yongsan",
    name: "용산",
    station: "용산역",
    line: "1호선·경의선",
    lat: 37.5298,
    lng: 126.9646,
    taxiScore: 3,
    description: "성장 중인 신흥 상권",
  },
  {
    id: "jamsil",
    name: "잠실",
    station: "잠실역",
    line: "2·8호선",
    lat: 37.5131,
    lng: 127.1000,
    taxiScore: 4,
    description: "강동권 중심 상권",
  },
  {
    id: "songridangil",
    name: "송리단길",
    station: "송파나루역",
    line: "9호선",
    lat: 37.5147,
    lng: 127.1105,
    taxiScore: 3,
    description: "잠실 옆 핫플, 이탈리안·일식 강세",
  },
  {
    id: "euljiro",
    name: "을지로",
    station: "을지로3가역",
    line: "2호선",
    lat: 37.5660,
    lng: 126.9920,
    taxiScore: 3,
    description: "트렌디 뉴레트로, 힙한 술집",
  },
  {
    id: "jongno",
    name: "종로/인사동",
    station: "종로3가역",
    line: "1·3·5호선",
    lat: 37.5706,
    lng: 126.9919,
    taxiScore: 3,
    description: "한식 전통 강세, 다양한 환승",
  },
  {
    id: "yeouido",
    name: "여의도",
    station: "여의도역",
    line: "5·9호선",
    lat: 37.5216,
    lng: 126.9244,
    taxiScore: 3,
    description: "금융권 직장인 밀집",
  },
  {
    id: "konkuk",
    name: "건대",
    station: "건대입구역",
    line: "2·7호선",
    lat: 37.5401,
    lng: 127.0705,
    taxiScore: 3,
    description: "강북 동부권 중심",
  },
  {
    id: "sinchon",
    name: "신촌",
    station: "신촌역",
    line: "2호선",
    lat: 37.5554,
    lng: 126.9368,
    taxiScore: 3,
    description: "대학가, 가성비 좋은 식당",
  },
];
